help

diff --git a/.github/workflows/cargo-publish.yml b/.github/workflows/cargo-publish.yml
--- a/.github/workflows/cargo-publish.yml
+++ b/.github/workflows/cargo-publish.yml
@@ -1,60 +1,75 @@
 name: Publish Rust crate
-
 on:
-  release:
-    # Use released instead of published, since we don't publish preview/beta
-    # versions. Users instead install them from the git repo.
-    types: [released]
-  workflow_dispatch:
-    inputs:
-      tag:
-        description: "Tag to publish (e.g., v1.0.0)"
-        required: true
-        type: string
+  push:
+    branches:
+      - main
 
 env:
-  # This env var is used by Swatinem/rust-cache@v2 for the cache
-  # key, so we set it to make sure it is always consistent.
+  CARGO_INCREMENTAL: '0'
   CARGO_TERM_COLOR: always
-  CARGO_INCREMENTAL: "0"
-  RUSTFLAGS: "-C debuginfo=0"
-
+  RUSTFLAGS: -C debuginfo=0
 jobs:
   build:
-    # Needs additional disk space for the full build.
-    runs-on: ubuntu-2404-8x-x64
-    timeout-minutes: 60
-    env:
-      # Need up-to-date compilers for kernels
-      CC: clang-18
-      CXX: clang++-18
     defaults:
       run:
         working-directory: .
+    env:
+      CC: clang-18
+      CXX: clang++-18
+    runs-on: ubuntu-2404-8x-x64
     steps:
+      - name: Start Energy Measurement
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          task: start-measurement
       - uses: actions/checkout@v4
       - uses: Swatinem/rust-cache@v2
         with:
           workspaces: rust
-      - name: Verify and checkout specified tag
-        if: github.event_name == 'workflow_dispatch'
-        run: |
-          git fetch --all --tags
-          if git rev-parse ${{ github.event.inputs.tag }} >/dev/null 2>&1; then
-            git checkout ${{ github.event.inputs.tag }}
-            echo "Successfully checked out tag ${{ github.event.inputs.tag }}"
-          else
-            echo "Error: Tag ${{ github.event.inputs.tag }} does not exist"
-            echo "Available tags:"
-            git tag -l
-            exit 1
-          fi
+      - if: github.event_name == 'workflow_dispatch'
+        name: Verify and checkout specified tag
+        run: "git fetch --all --tags\nif git rev-parse ${{ github.event.inputs.tag\
+          \ }} >/dev/null 2>&1; then\n  git checkout ${{ github.event.inputs.tag }}\n\
+          \  echo \"Successfully checked out tag ${{ github.event.inputs.tag }}\"\n\
+          else\n  echo \"Error: Tag ${{ github.event.inputs.tag }} does not exist\"\
+          \n  echo \"Available tags:\"\n  git tag -l\n  exit 1\nfi\n"
+      - id: measurement-4
+        name: Record Measurement After Verify and checkout specified tag
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Verify and checkout specified tag
+          task: get-measurement
       - name: Install dependencies
-        run: |
-          sudo apt update
+        run: 'sudo apt update
+
           sudo apt install -y protobuf-compiler libssl-dev
+
+          '
+      - id: measurement-6
+        name: Record Measurement After Install dependencies
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Install dependencies
+          task: get-measurement
       - uses: albertlockett/publish-crates@v2.2
         with:
-          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
-          args: "--all-features"
+          args: --all-features
           path: .
+          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
+      - id: display-measurement
+        name: Display Energy Results
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          task: display-results
+      - name: Save Total Energy Consumption Data
+        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
+      - name: Upload Energy Consumption Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: total-energy-consumption
+          path: total_energy_consumption.json
+    timeout-minutes: 60
diff --git a/.github/workflows/file_verification.yml b/.github/workflows/file_verification.yml
--- a/.github/workflows/file_verification.yml
+++ b/.github/workflows/file_verification.yml
@@ -1,64 +1,129 @@
 name: Lance File Write Read Round Trip Verification
-
-on: 
-  workflow_dispatch:
+on:
+  push:
+    branches:
+      - main
 
 jobs:
   run:
     runs-on: ubuntu-24.04
     steps:
+      - name: Start Energy Measurement
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          task: start-measurement
       - name: Checkout repository
         uses: actions/checkout@v4
-
       - name: Set up Python
         uses: actions/setup-python@v5
         with:
           python-version: '3.11'
-
       - name: Install Build Requirements
-        run: |
-          sudo apt update
+        run: 'sudo apt update
+
           sudo apt install -y protobuf-compiler
 
+          '
+      - id: measurement-4
+        name: Record Measurement After Install Build Requirements
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Install Build Requirements
+          task: get-measurement
       - name: Validate AWS Credentials
-        run: |
-          if [ -z "${{ secrets.LANCEDB_S3_READER_ACCESS_KEY }}" ] || [ -z "${{ secrets.LANCEDB_S3_READER_SECRET }}" ]; then
-            echo "ERROR: AWS credentials are not properly set"
-            exit 1
-          fi
-          echo "AWS credentials validation successful"
-
+        run: "if [ -z \"${{ secrets.LANCEDB_S3_READER_ACCESS_KEY }}\" ] || [ -z \"\
+          ${{ secrets.LANCEDB_S3_READER_SECRET }}\" ]; then\n  echo \"ERROR: AWS credentials\
+          \ are not properly set\"\n  exit 1\nfi\necho \"AWS credentials validation\
+          \ successful\"\n"
+      - id: measurement-6
+        name: Record Measurement After Validate AWS Credentials
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Validate AWS Credentials
+          task: get-measurement
       - name: Set up AWS CLI
         uses: aws-actions/configure-aws-credentials@v3
         with:
           aws-access-key-id: ${{ secrets.LANCEDB_S3_READER_ACCESS_KEY }}
-          aws-secret-access-key: ${{ secrets.LANCEDB_S3_READER_SECRET }}
           aws-region: us-east-2
-
+          aws-secret-access-key: ${{ secrets.LANCEDB_S3_READER_SECRET }}
       - name: Prepare Test Environment
-        run: |
-          BUCKET_NAME="lance-ci-bucket"
+        run: 'BUCKET_NAME="lance-ci-bucket"
+
           mkdir -p .github/workflows/file_veification/test_files
+
           aws s3 ls s3://$BUCKET_NAME
-          aws s3 cp s3://$BUCKET_NAME .github/workflows/file_verification/test_files --recursive
+
+          aws s3 cp s3://$BUCKET_NAME .github/workflows/file_verification/test_files
+          --recursive
+
           ls -l .github/workflows/file_verification/test_files
 
+          '
+      - id: measurement-9
+        name: Record Measurement After Prepare Test Environment
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Prepare Test Environment
+          task: get-measurement
       - name: Build Lance
-        working-directory: ./python
-        run: |
-          python -m venv venv
+        run: 'python -m venv venv
+
           source venv/bin/activate
+
           pip install pyarrow maturin
+
           maturin develop --release
 
+          '
+        working-directory: ./python
+      - id: measurement-11
+        name: Record Measurement After Build Lance
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Build Lance
+          task: get-measurement
       - name: Test Lance File Write Read Round Trip
-        run: |
-          source python/venv/bin/activate
+        run: 'source python/venv/bin/activate
+
           cd .github/workflows/file_verification
+
           python test_write_read.py
 
-
+          '
+      - id: measurement-13
+        name: Record Measurement After Test Lance File Write Read Round Trip
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Test Lance File Write Read Round Trip
+          task: get-measurement
       - name: Cleanup
-        run: |
-          rm -rf .github/workflows/file_verification/test_files
-          echo "Cleanup completed: Test files removed"
+        run: 'rm -rf .github/workflows/file_verification/test_files
+
+          echo "Cleanup completed: Test files removed"'
+      - id: measurement-15
+        name: Record Measurement After Cleanup
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          label: Cleanup
+          task: get-measurement
+      - id: display-measurement
+        name: Display Energy Results
+        uses: green-coding-solutions/eco-ci-energy-estimation@v4
+        with:
+          json-output: true
+          task: display-results
+      - name: Save Total Energy Consumption Data
+        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
+      - name: Upload Energy Consumption Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: total-energy-consumption
+          path: total_energy_consumption.json
